/**
 * Helper function to Base64-URL-encode a buffer of random bytes.
 * This is a URL-safe version of Base64 encoding, required by the PKCE spec.
 * @param buffer The Uint8Array buffer to encode.
 * @returns The Base64-URL-encoded string.
 */
function base64urlEncode(buffer: Uint8Array): string {
  const base64 = window.btoa(String.fromCharCode(...buffer));
  return base64
    .replace(/\+/g, '-') // Replace '+' with '-'
    .replace(/\//g, '_') // Replace '/' with '_'
    .replace(/=+$/, ''); // Remove trailing '='
}

/**
 * Generates a high-entropy random string to be used as the PKCE code verifier.
 * The verifier is a cryptographically random string that the client holds secret.
 * @returns A URL-safe, Base64-encoded random string.
 */
export function generateCodeVerifier(): string {
  // Create an array of 64 random bytes
  const randomBytes = new Uint8Array(64);
  window.crypto.getRandomValues(randomBytes);
  // Encode the bytes into a URL-safe string
  return base64urlEncode(randomBytes);
}

/**
 * Hashes and encodes the verifier string to create the PKCE code challenge.
 * The challenge is sent to the authorization server at the beginning of the flow.
 * @param verifier The code verifier generated by `generateCodeVerifier`.
 * @returns A promise that resolves to the URL-safe, Base64-encoded SHA-256 hash of the verifier.
 */
export async function generateCodeChallenge(verifier: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);
  // Hash the verifier using the SHA-256 algorithm
  const digest = await window.crypto.subtle.digest('SHA-256', data);
  // Encode the hash into a URL-safe string
  return base64urlEncode(new Uint8Array(digest));
}

